// 江西省前60所高校基础信息数据
// 数据来源：各高校官网、软科/校友会排名、新生群收集
// 最后更新：2026年7月

const universities = [
  {
    id: 1,
    name: "南昌大学",
    level: "211 / 双一流",
    city: "南昌",
    website: "https://www.ncu.edu.cn",
    logo: "",
    militaryTraining: "9月中旬开始，持续约14天，在校内进行",
    dormitory: "前湖校区为主，4-6人间，有空调、独卫、热水器，部分楼栋有电梯",
    cafeteria: "多个食堂分布各校区，前湖校区有9个食堂，价格实惠，品种丰富",
    campusArea: "约4000亩（前湖主校区）",
    majors: "材料科学与工程（双一流）、临床医学、食品科学、化学",
    tuition: "4500-5550元/年（普通专业）",
    transportation: "地铁1号线可达前湖校区，公交线路多，校门口有共享单车",
    genderRatio: "男:女 ≈ 1:1",
    clubs: "100+社团，学生会、青协等组织活跃",
    description: "江西省唯一的211工程和双一流建设高校，综合实力省内第一"
  },
  {
    id: 2,
    name: "江西财经大学",
    level: "省重点 / 财经名校",
    city: "南昌",
    website: "https://www.jxufe.edu.cn",
    logo: "",
    militaryTraining: "9月中上旬，约10-12天",
    dormitory: "蛟桥园校区为主，4人间为主，有空调、独卫，环境较好",
    cafeteria: "蛟桥园有5个食堂，麦庐园有3个食堂，伙食口碑好",
    campusArea: "约2200亩（含蛟桥园、麦庐园等校区）",
    majors: "应用经济学（A-）、统计学（A-）、工商管理、法学",
    tuition: "4660-5220元/年（普通专业）",
    transportation: "地铁1号线到蛟桥园，交通便利",
    genderRatio: "男:女 ≈ 2:3",
    clubs: "80+社团，财经类社团特色突出",
    description: "全国财经类院校排名前7，应用经济学和统计学为A-学科"
  },
  {
    id: 3,
    name: "江西师范大学",
    level: "省重点 / 省属重点",
    city: "南昌",
    website: "https://www.jxnu.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "瑶湖校区4人间，上床下桌，独卫+空调+热水器，每层有洗衣机烘干机，详见子页面",
    cafeteria: "瑶湖校区有5个食堂，另有美食街",
    campusArea: "约3000亩（瑶湖校区）",
    majors: "化学、教育学、心理学、汉语言文学、马克思主义理论",
    tuition: "4380-4960元/年（普通专业）",
    transportation: "地铁1号线瑶湖西站，公交220路等",
    genderRatio: "男:女 ≈ 1:2",
    clubs: "100+社团，师范类特色社团丰富",
    description: "江西省最好的师范类院校，化学和马克思主义理论为优势学科",
    resources: {
      photos: true,
      transfer: true,
      url: "江西师范大学/index.html"
    }
  },
  {
    id: 4,
    name: "江西理工大学",
    level: "省重点",
    city: "赣州/南昌",
    website: "https://www.jxust.edu.cn",
    logo: "",
    militaryTraining: "9月中下旬，约14天",
    dormitory: "三江校区4人间（上床下桌，独卫+空调+热水器），红旗校区4-6人间（部分无独卫，每层公共淋浴房），南昌校区4人间（独卫+空调），详见子页面",
    cafeteria: "四个校区各有多家食堂，赣南特色美食",
    campusArea: "四大校区共约5000亩（三江校区65万m²）",
    majors: "冶金工程（国家级特色）、矿业工程、材料科学、稀土工程、机械工程、自动化、电气工程、计算机、会计学",
    tuition: "4270-4940元/年",
    transportation: "赣州站公交直达，南昌校区近地铁1号线双港站",
    genderRatio: "男:女 ≈ 3:1",
    clubs: "70+社团",
    description: "省部共建高校，原冶金部直属，被誉为'有色冶金人才摇篮''稀土科教黄埔'，拥有本-硕-博完整学位授予权",
    resources: {
      photos: true,
      transfer: true,
      url: "江西理工大学/index.html"
    }
  },
  {
    id: 5,
    name: "东华理工大学",
    level: "省重点",
    city: "南昌/抚州",
    website: "https://www.ecut.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "广兰4人间上床下桌（公共卫浴），枫林4人间（部分独卫），抚州4-6人间（玉茗独卫），均配空调，详见子页面",
    cafeteria: "各校区有多家食堂，价格适中",
    campusArea: "约2500亩（南昌+抚州共4校区）",
    majors: "核工程与核技术（国家级特色）、资源勘查工程、勘查技术与工程、水文与水资源工程、环境工程",
    tuition: "4270-4940元/年",
    transportation: "南昌校区交通便利，抚州校区近火车站",
    genderRatio: "男:女 ≈ 3:2",
    clubs: "60+社团",
    description: "中国核工业第一所高等学府，四方共建，核科学+地学双核心，5个ESI前1%学科，被誉为'中国核地学人才摇篮'",
    resources: {
      photos: true,
      transfer: false,
      url: "东华理工大学/index.html"
    }
  },
  {
    id: 6,
    name: "江西农业大学",
    level: "省重点",
    city: "南昌",
    website: "https://www.jxau.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "绝大多数4人间，上床下桌，配空调+衣柜，部分有独卫阳台，每栋有公共洗衣房烘干机，详见子页面",
    cafeteria: "有3个主要食堂，另有小吃街",
    campusArea: "约16000亩（含实验田，全省最大）",
    majors: "农学、林学、动物科学、农林经济管理、生物工程（均为国家级特色）",
    tuition: "4090-4530元/年",
    transportation: "地铁1号线双港站附近，公交240路等",
    genderRatio: "男:女 ≈ 1:1",
    clubs: "70+社团",
    description: "省部共建，农业农村部+国家林草局共建，百年老校（1905年），校园面积全省最大，畜牧学冲击双一流，ESI前1%学科6个",
    resources: {
      photos: true,
      transfer: true,
      url: "江西农业大学/index.html"
    }
  },
  {
    id: 7,
    name: "南昌航空大学",
    level: "省重点",
    city: "南昌",
    website: "https://www.nchu.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "前湖校区，4人间为主，有空调、独卫、热水器",
    cafeteria: "有3个主要食堂，航空航天主题餐厅有特色",
    campusArea: "约3000亩",
    majors: "航空宇航科学、材料科学、测控技术、飞行器设计",
    tuition: "4270-4530元/年",
    transportation: "地铁2号线可达，前湖大道快速路旁",
    genderRatio: "男:女 ≈ 7:3",
    clubs: "80+社团，航模社团全国知名",
    description: "航空特色鲜明，与中航工业集团合作紧密"
  },
  {
    id: 8,
    name: "华东交通大学",
    level: "省重点",
    city: "南昌",
    website: "https://www.ecjtu.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "经开区校区，4人间为主，有空调、独卫、热水器",
    cafeteria: "有4个食堂，南北风味齐全",
    campusArea: "约2800亩",
    majors: "交通运输工程、土木工程、机械工程、电气工程",
    tuition: "4270-4940元/年",
    transportation: "地铁1号线双港站直达",
    genderRatio: "男:女 ≈ 3:1",
    clubs: "70+社团",
    description: "交通领域特色高校，铁路系统就业率高，国企就业率超40%"
  },
  {
    id: 9,
    name: "景德镇陶瓷大学",
    level: "省重点 / 特色名校",
    city: "景德镇",
    website: "https://www.jci.edu.cn",
    logo: "",
    militaryTraining: "9月中下旬，约10-14天",
    dormitory: "湘湖校区，4人间为主，有空调、独卫",
    cafeteria: "有2个主要食堂，景德镇本地美食有特色",
    campusArea: "约2000亩",
    majors: "陶瓷艺术设计、材料科学（陶瓷方向）、美术学、设计学",
    tuition: "9600元/年（艺术类），4270元/年（普通类）",
    transportation: "景德镇站公交可达，景德镇有机场",
    genderRatio: "男:女 ≈ 2:3",
    clubs: "50+社团，陶瓷艺术社团全国独一",
    description: "中国唯一以陶瓷命名的高校，陶瓷艺术设计全国顶尖"
  },
  {
    id: 10,
    name: "赣南师范大学",
    level: "省属重点",
    city: "赣州",
    website: "https://www.gnnu.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "蓉江校区，4-6人间，有空调、独卫",
    cafeteria: "有3个食堂，赣南客家美食",
    campusArea: "约2200亩",
    majors: "教育学、汉语言文学、历史学、化学",
    tuition: "4010-4530元/年",
    transportation: "赣州站/赣州西站公交可达",
    genderRatio: "男:女 ≈ 1:2",
    clubs: "60+社团",
    description: "赣南地区最好的师范院校，红色文化研究特色鲜明"
  },
  {
    id: 11,
    name: "江西科技师范大学",
    level: "省属",
    city: "南昌",
    website: "https://www.jxstnu.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "枫林校区/红角洲校区，4-6人间，有空调",
    cafeteria: "各校区有食堂，价格实惠",
    campusArea: "约2000亩",
    majors: "教育学、旅游管理、化学工程、电子信息",
    tuition: "4270-4940元/年",
    transportation: "地铁可达，公交线路多",
    genderRatio: "男:女 ≈ 2:3",
    clubs: "60+社团",
    description: "职业师范教育特色，培养应用型人才为主"
  },
  {
    id: 12,
    name: "江西水利电力大学",
    level: "省属",
    city: "南昌",
    website: "https://www.juwp.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "瑶湖校区，4人间为主，有空调、独卫",
    cafeteria: "有3个食堂",
    campusArea: "约2000亩",
    majors: "水利工程、土木工程、电气工程、计算机科学",
    tuition: "4270-4790元/年",
    transportation: "地铁1号线瑶湖西站附近",
    genderRatio: "男:女 ≈ 3:1",
    clubs: "50+社团",
    description: "水利电力特色鲜明，原水利部直属院校",
    resources: {
      photos: true,
      transfer: true,
      url: "江西水利电力大学/index.html"
    }
  },
  {
    id: 13,
    name: "井冈山大学",
    level: "省属",
    city: "吉安",
    website: "https://www.jgsu.edu.cn",
    logo: "",
    militaryTraining: "9月中下旬，约14天",
    dormitory: "青原校区，4-6人间，有空调、部分独卫",
    cafeteria: "有3个食堂，吉安本地美食",
    campusArea: "约2500亩",
    majors: "医学、教育学、生物科学、汉语言文学",
    tuition: "4010-4790元/年",
    transportation: "吉安站公交直达",
    genderRatio: "男:女 ≈ 1:1",
    clubs: "60+社团，红色文化社团特色",
    description: "以井冈山精神办学，红色文化教育基地"
  },
  {
    id: 14,
    name: "江西中医药大学",
    level: "省重点 / 中医药特色",
    city: "南昌",
    website: "https://www.jxutcm.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约10-14天",
    dormitory: "湾里校区/阳明校区，4人间为主，有空调、独卫",
    cafeteria: "有药膳食堂为特色，还有常规食堂",
    campusArea: "约2000亩",
    majors: "中医学、中药学、针灸推拿、药学",
    tuition: "5220元/年（医学类）",
    transportation: "湾里校区较偏，有公交直达市区",
    genderRatio: "男:女 ≈ 1:2",
    clubs: "50+社团，中医药文化社团有特色",
    description: "全国中医药类院校排名前列，中药学为国家级特色专业"
  },
  {
    id: 15,
    name: "宜春学院",
    level: "省属",
    city: "宜春",
    website: "https://www.ycu.edu.cn",
    logo: "",
    militaryTraining: "9月中下旬，约14天",
    dormitory: "学府校区，4-6人间，逐步安装空调",
    cafeteria: "有2个食堂，价格实惠",
    campusArea: "约2000亩",
    majors: "医学、农学、师范类、工学",
    tuition: "4010-4790元/年",
    transportation: "宜春站公交可达",
    genderRatio: "男:女 ≈ 1:1",
    clubs: "50+社团",
    description: "综合性本科院校，医学和农学有区域优势"
  },
  {
    id: 16,
    name: "赣南医科大学",
    level: "省属",
    city: "赣州",
    website: "https://www.gmu.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "黄金校区，4-6人间，有空调、独卫",
    cafeteria: "有2个食堂",
    campusArea: "约2000亩",
    majors: "临床医学、护理学、药学、预防医学",
    tuition: "4790-5220元/年",
    transportation: "赣州站公交可达",
    genderRatio: "男:女 ≈ 2:3",
    clubs: "40+社团",
    description: "赣南地区唯一的医科大学，为基层培养医疗人才"
  },
  {
    id: 17,
    name: "上饶师范学院",
    level: "省属",
    city: "上饶",
    website: "https://www.sru.edu.cn",
    logo: "",
    militaryTraining: "9月中下旬，约14天",
    dormitory: "信州校区，4-6人间，部分有空调",
    cafeteria: "有2个食堂",
    campusArea: "约1200亩",
    majors: "教育学、汉语言文学、数学、化学",
    tuition: "4010-4530元/年",
    transportation: "上饶站公交可达",
    genderRatio: "男:女 ≈ 1:2",
    clubs: "40+社团",
    description: "赣东北地区主要师范院校，为基础教育培养师资"
  },
  {
    id: 18,
    name: "南昌师范学院",
    level: "省属",
    city: "南昌",
    website: "https://www.nctc.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "昌北校区，4-6人间，有空调",
    cafeteria: "有2个食堂",
    campusArea: "约600亩",
    majors: "教育学、汉语言文学、英语、数学",
    tuition: "4010-4530元/年",
    transportation: "地铁1号线可达",
    genderRatio: "男:女 ≈ 1:3",
    clubs: "40+社团",
    description: "南昌市属师范院校，培养中小学教师"
  },
  {
    id: 19,
    name: "景德镇学院",
    level: "省属",
    city: "景德镇",
    website: "https://www.jdzu.edu.cn",
    logo: "",
    militaryTraining: "9月中下旬，约14天",
    dormitory: "浮梁校区，4-6人间，有空调",
    cafeteria: "有2个食堂",
    campusArea: "约1000亩",
    majors: "陶瓷艺术、工艺美术、教育学、工学",
    tuition: "4010-8000元/年",
    transportation: "景德镇站公交可达",
    genderRatio: "男:女 ≈ 1:2",
    clubs: "30+社团",
    description: "地方应用型本科院校，陶瓷和工艺美术有区域特色"
  },
  {
    id: 20,
    name: "新余学院",
    level: "省属",
    city: "新余",
    website: "https://www.xyc.edu.cn",
    logo: "",
    militaryTraining: "9月中下旬，约14天",
    dormitory: "渝水校区，4-6人间，有空调",
    cafeteria: "有2个食堂",
    campusArea: "约1200亩",
    majors: "新能源科学、机械工程、计算机科学",
    tuition: "4010-4790元/年",
    transportation: "新余站/新余北站公交可达",
    genderRatio: "男:女 ≈ 3:2",
    clubs: "40+社团",
    description: "新能源领域特色，与新余光伏产业紧密对接"
  },
  {
    id: 21,
    name: "九江学院",
    level: "省属",
    city: "九江",
    website: "https://www.jju.edu.cn",
    logo: "",
    militaryTraining: "9月中下旬，约14天",
    dormitory: "庐山区校区，4-6人间，部分有空调",
    cafeteria: "有3个食堂，九江鱼宴有特色",
    campusArea: "约2000亩",
    majors: "医学、工学、管理学、文学",
    tuition: "4010-4790元/年",
    transportation: "九江站公交可达，近庐山景区",
    genderRatio: "男:女 ≈ 1:1",
    clubs: "50+社团",
    description: "综合性本科院校，坐落在庐山脚下，环境优美"
  },
  {
    id: 22,
    name: "江西警察学院",
    level: "省属 / 公安类",
    city: "南昌",
    website: "https://www.jxga.edu.cn",
    logo: "",
    militaryTraining: "入学即开始，约1个月（含警务化训练）",
    dormitory: "湾里校区，4人间，有空调、独卫，警务化管理",
    cafeteria: "有食堂，统一就餐管理",
    campusArea: "约1000亩",
    majors: "侦查学、治安学、刑事科学技术、交通管理工程",
    tuition: "4380-4940元/年",
    transportation: "公交可达",
    genderRatio: "男:女 ≈ 4:1",
    clubs: "30+社团，警务技能类社团为主",
    description: "江西省唯一公安本科院校，实行警务化管理"
  },
  {
    id: 23,
    name: "萍乡学院",
    level: "省属",
    city: "萍乡",
    website: "https://www.pxc.edu.cn",
    logo: "",
    militaryTraining: "9月中下旬，约14天",
    dormitory: "安源校区，4-6人间，部分有空调",
    cafeteria: "有2个食堂",
    campusArea: "约1000亩",
    majors: "工学、管理学、教育学",
    tuition: "4010-4530元/年",
    transportation: "萍乡站/萍乡北站公交可达",
    genderRatio: "男:女 ≈ 1:1",
    clubs: "30+社团",
    description: "赣西地区应用型本科院校，工科为主"
  },
  {
    id: 24,
    name: "豫章师范学院",
    level: "省属",
    city: "南昌",
    website: "https://www.yuznu.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "红谷滩校区，4-6人间，有空调",
    cafeteria: "有食堂",
    campusArea: "约500亩",
    majors: "学前教育、小学教育、特殊教育、艺术教育",
    tuition: "4010-4530元/年",
    transportation: "地铁2号线可达",
    genderRatio: "男:女 ≈ 1:4",
    clubs: "30+社团",
    description: "以学前教育为特色的师范院校"
  },
  {
    id: 25,
    name: "赣东学院",
    level: "省属",
    city: "抚州",
    website: "https://www.gdc.edu.cn",
    logo: "",
    militaryTraining: "9月中下旬，约14天",
    dormitory: "临川校区，4-6人间，有空调",
    cafeteria: "有食堂",
    campusArea: "约800亩",
    majors: "计算机科学、电子信息、管理学",
    tuition: "4010-4790元/年",
    transportation: "抚州站公交可达",
    genderRatio: "男:女 ≈ 3:2",
    clubs: "30+社团",
    description: "由东华理工大学长江学院转设，应用型本科院校"
  },
  {
    id: 26,
    name: "赣南科技学院",
    level: "省属",
    city: "赣州",
    website: "https://www.gnust.edu.cn",
    logo: "",
    militaryTraining: "9月中下旬，约14天",
    dormitory: "蓉江校区，4-6人间，有空调",
    cafeteria: "有食堂",
    campusArea: "约800亩",
    majors: "冶金工程、材料科学、机械工程、计算机科学",
    tuition: "4010-4790元/年",
    transportation: "赣州站公交可达",
    genderRatio: "男:女 ≈ 3:1",
    clubs: "30+社团",
    description: "由江西理工大学应用科学学院转设，工科特色"
  },
  {
    id: 27,
    name: "南昌医学院",
    level: "省属",
    city: "南昌",
    website: "https://www.ncmc.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "湾里校区，4-6人间，有空调",
    cafeteria: "有食堂",
    campusArea: "约800亩",
    majors: "临床医学、护理学、药学、医学检验",
    tuition: "4790-5220元/年",
    transportation: "公交可达",
    genderRatio: "男:女 ≈ 1:2",
    clubs: "30+社团",
    description: "2021年新设医科院校，由江西中医药大学科技学院转设"
  },
  {
    id: 28,
    name: "江西飞行学院",
    level: "省属",
    city: "南昌",
    website: "https://www.jxfly.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天（含准军事化管理训练）",
    dormitory: "昌北校区，4人间，有空调、独卫",
    cafeteria: "有食堂",
    campusArea: "约1000亩",
    majors: "飞行技术、空中乘务、航空服务、航空工程",
    tuition: "4270-8000元/年（飞行技术另计）",
    transportation: "公交可达",
    genderRatio: "男:女 ≈ 3:2",
    clubs: "30+社团",
    description: "2024年新设本科院校，由江西经济管理干部学院和江西飞行学校合并组建"
  },
  {
    id: 29,
    name: "南昌理工学院",
    level: "民办本科 / 全国民办前5",
    city: "南昌",
    website: "https://www.nclg.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "经开区校区，4-6人间，有空调、独卫，住宿条件较好",
    cafeteria: "有多个食堂和美食街",
    campusArea: "约2600亩",
    majors: "计算机科学、电子信息、机械工程、管理学",
    tuition: "15000-21000元/年",
    transportation: "地铁1号线可达",
    genderRatio: "男:女 ≈ 3:2",
    clubs: "60+社团",
    description: "江西省规模最大的民办本科院校，全国民办高校排名前5"
  },
  {
    id: 30,
    name: "江西科技学院",
    level: "民办本科",
    city: "南昌",
    website: "https://www.jxut.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "高新区校区，4人间为主，有空调、独卫、热水器",
    cafeteria: "有多个食堂",
    campusArea: "约2000亩",
    majors: "计算机科学、汽车工程、管理学、艺术设计",
    tuition: "15000-20000元/年",
    transportation: "地铁1号线艾溪湖东站附近",
    genderRatio: "男:女 ≈ 3:2",
    clubs: "50+社团",
    description: "以工科为主的民办本科院校，汽车工程为特色"
  },
  {
    id: 31,
    name: "南昌大学科学技术学院",
    level: "独立学院",
    city: "九江",
    website: "https://www.ndkj.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "共青城校区，4人间为主，有空调、独卫、热水器，住宿条件较好",
    cafeteria: "有2个食堂，品种丰富",
    campusArea: "约1000亩",
    majors: "计算机科学、会计学、汉语言文学、机械工程",
    tuition: "13000-15500元/年",
    transportation: "共青城站公交可达，高铁站附近",
    genderRatio: "男:女 ≈ 1:1",
    clubs: "40+社团，依托南昌大学资源",
    description: "南昌大学主办的独立学院，位于共青城大学城"
  },
  {
    id: 32,
    name: "江西师范大学科学技术学院",
    level: "独立学院",
    city: "九江",
    website: "https://www.jxsdkj.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "共青城校区，4人间，有空调、独卫",
    cafeteria: "有2个食堂",
    campusArea: "约800亩",
    majors: "教育学、汉语言文学、英语、计算机科学",
    tuition: "13000-15500元/年",
    transportation: "共青城站公交可达",
    genderRatio: "男:女 ≈ 1:3",
    clubs: "30+社团",
    description: "江西师范大学主办的独立学院，师范教育有特色"
  },
  {
    id: 33,
    name: "江西财经大学现代经济管理学院",
    level: "独立学院",
    city: "九江",
    website: "https://www.jcxjg.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约12天",
    dormitory: "共青城校区，4人间为主，有空调、独卫",
    cafeteria: "有2个食堂",
    campusArea: "约700亩",
    majors: "会计学、金融学、工商管理、法学",
    tuition: "13000-15500元/年",
    transportation: "共青城站可达",
    genderRatio: "男:女 ≈ 2:3",
    clubs: "30+社团，经管类社团突出",
    description: "江西财经大学主办的独立学院，经管学科有优势"
  },
  {
    id: 34,
    name: "南昌航空大学科技学院",
    level: "独立学院",
    city: "九江",
    website: "https://www.nckj.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "共青城校区，4人间为主，有空调、独卫",
    cafeteria: "有食堂",
    campusArea: "约800亩",
    majors: "飞行器制造工程、计算机科学、机械设计、电子商务",
    tuition: "13000-15500元/年",
    transportation: "共青城站可达",
    genderRatio: "男:女 ≈ 3:1",
    clubs: "30+社团",
    description: "南昌航空大学主办的独立学院，航空特色专业"
  },
  {
    id: 35,
    name: "江西农业大学南昌商学院",
    level: "独立学院",
    city: "九江",
    website: "https://www.ncsxy.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "共青城校区，4人间，有空调、独卫",
    cafeteria: "有食堂",
    campusArea: "约600亩",
    majors: "会计学、经济学、工商管理、电子商务",
    tuition: "13000-15500元/年",
    transportation: "共青城站可达",
    genderRatio: "男:女 ≈ 1:1",
    clubs: "30+社团",
    description: "江西农业大学主办的独立学院，商科为特色方向"
  },
  {
    id: 36,
    name: "南昌大学共青学院",
    level: "独立学院",
    city: "九江",
    website: "https://www.ndgy.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "共青城校区，4人间，有空调、独卫",
    cafeteria: "有食堂",
    campusArea: "约1000亩",
    majors: "汉语言文学、英语、工商管理、国际经济与贸易",
    tuition: "13000-15500元/年",
    transportation: "共青城站公交可达",
    genderRatio: "男:女 ≈ 2:3",
    clubs: "30+社团",
    description: "南昌大学在共青城设立的独立学院，文科见长"
  },
  {
    id: 37,
    name: "南昌交通学院",
    level: "民办本科",
    city: "南昌",
    website: "https://www.nctu.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "南昌校区/靖安校区，4人间，有空调、独卫",
    cafeteria: "有2个食堂",
    campusArea: "约1200亩（含靖安校区）",
    majors: "土木工程、交通运输、计算机科学、会计学",
    tuition: "15000-19000元/年",
    transportation: "南昌校区近地铁，靖安校区较偏",
    genderRatio: "男:女 ≈ 3:1",
    clubs: "40+社团",
    description: "由华东交通大学理工学院转设，交通土建为特色"
  },
  {
    id: 38,
    name: "江西工程学院",
    level: "民办本科",
    city: "新余",
    website: "https://www.jxue.edu.cn",
    logo: "",
    militaryTraining: "9月中下旬，约14天",
    dormitory: "仙女湖校区，4-6人间，有空调、独卫",
    cafeteria: "有2个食堂",
    campusArea: "约1000亩",
    majors: "电子信息工程、计算机科学、机械设计、软件工程",
    tuition: "13000-17000元/年",
    transportation: "新余站/新余北站公交可达",
    genderRatio: "男:女 ≈ 3:1",
    clubs: "30+社团",
    description: "以工科为主的民办本科院校，电子信息为特色方向"
  },
  {
    id: 39,
    name: "南昌工学院",
    level: "民办本科",
    city: "南昌",
    website: "https://www.ncgxy.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "红谷滩校区，4人间为主，有空调、独卫",
    cafeteria: "有2个食堂，另有小吃街",
    campusArea: "约1000亩",
    majors: "机械工程、电子信息、会计学、土木工程",
    tuition: "13000-18000元/年",
    transportation: "地铁可达",
    genderRatio: "男:女 ≈ 3:2",
    clubs: "40+社团",
    description: "民办应用型本科院校，工科和管理学科并重"
  },
  {
    id: 40,
    name: "江西应用科技学院",
    level: "民办本科",
    city: "南昌",
    website: "https://www.jxuas.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "湾里校区，4人间，有空调、独卫",
    cafeteria: "有食堂",
    campusArea: "约1000亩",
    majors: "人工智能、大数据、物联网工程、电子商务",
    tuition: "14000-19000元/年",
    transportation: "公交可达",
    genderRatio: "男:女 ≈ 2:1",
    clubs: "30+社团",
    description: "聚焦应用型人才培养，新兴工科专业布局多"
  },
  {
    id: 41,
    name: "江西服装学院",
    level: "民办本科",
    city: "南昌",
    website: "https://www.jift.edu.cn",
    logo: "",
    militaryTraining: "9月中旬，约14天",
    dormitory: "向塘校区，4人间为主，有空调、独卫",
    cafeteria: "有食堂",
    campusArea: "约800亩",
    majors: "服装设计与工程、服装表演、数字媒体艺术、市场营销",
    tuition: "15000-19000元/年",
    transportation: "向塘站附近，南昌市区有班车",
    genderRatio: "男:女 ≈ 1:3",
    clubs: "30+社团，服装设计类社团全国知名",
    description: "全国知名的服装类本科院校，服装设计优势突出"
  },
  {
    id: 42,
    name: "南昌职业大学",
    level: "民办职业本科",
    city: "南昌",
    website: "https://www.nvu.edu.cn",
    logo: "",
    militaryTraining: "9月下旬，约14天",
    dormitory: "安义校区，4人间为主，有空调、独卫",
    cafeteria: "有食堂",
    campusArea: "约1200亩",
    majors: "机械设计制造、电子商务、计算机应用工程、市场营销",
    tuition: "12000-16000元/年",
    transportation: "南昌市区有公交/班车，距离市区较远",
    genderRatio: "男:女 ≈ 3:2",
    clubs: "30+社团",
    description: "江西省首批本科层次职业教育试点院校，侧重技能培养"
  },
  {
    id: 43,
    name: "江西软件职业技术大学",
    level: "民办职业本科",
    city: "南昌",
    website: "https://www.jxuspt.edu.cn",
    logo: "",
    militaryTraining: "9月下旬，约14天",
    dormitory: "经开区校区，4人间为主，有空调、独卫",
    cafeteria: "有食堂",
    campusArea: "约1000亩",
    majors: "软件工程、区块链技术、人工智能、电子商务",
    tuition: "12000-17000元/年",
    transportation: "公交可达",
    genderRatio: "男:女 ≈ 4:1",
    clubs: "30+社团，编程技术社团活跃",
    description: "全国首批软件职业技术大学，先锋软件集团创办"
  },
  {
    id: 44,
    name: "景德镇艺术职业大学",
    level: "民办职业本科",
    city: "景德镇",
    website: "https://www.jdzu-sca.edu.cn",
    logo: "",
    militaryTraining: "9月中下旬，约14天",
    dormitory: "浮梁校区，4人间，有空调、独卫",
    cafeteria: "有食堂",
    campusArea: "约600亩",
    majors: "陶瓷艺术设计、雕塑、工艺美术、数字媒体艺术",
    tuition: "13000-18000元/年",
    transportation: "景德镇站公交可达",
    genderRatio: "男:女 ≈ 2:3",
    clubs: "20+社团，陶瓷艺术社团有特色",
    description: "以陶瓷和艺术为特色的职业本科院校"
  },
  {
    id: 45,
    name: "九江职业技术学院",
    level: "公办高职 / 双高计划",
    city: "九江",
    website: "https://www.jvtc.jx.cn",
    logo: "",
    militaryTraining: "10月初，约10-14天",
    dormitory: "濂溪校区/十里校区，4-6人间，有空调",
    cafeteria: "有2个食堂，价格实惠",
    campusArea: "约1200亩",
    majors: "船舶工程、数控技术、汽车检测、计算机应用",
    tuition: "5000-6000元/年",
    transportation: "九江站公交可达",
    genderRatio: "男:女 ≈ 4:1",
    clubs: "40+社团",
    description: "江西省最好的高职院校之一，双高计划建设单位，船舶和制造类为特色"
  },
  {
    id: 46,
    name: "江西财经职业学院",
    level: "公办高职 / 国家骨干",
    city: "九江",
    website: "https://www.jxvc.jx.cn",
    logo: "",
    militaryTraining: "10月初，约10天",
    dormitory: "浔阳校区，4-6人间，有空调",
    cafeteria: "有2个食堂",
    campusArea: "约800亩",
    majors: "大数据与会计、金融管理、电子商务、市场营销",
    tuition: "5000元/年",
    transportation: "九江站公交可达",
    genderRatio: "男:女 ≈ 1:2",
    clubs: "40+社团",
    description: "全国财经类高职院校排名前10，国家骨干高职院校"
  },
  {
    id: 47,
    name: "江西现代职业技术学院",
    level: "公办高职 / 双高计划",
    city: "南昌",
    website: "https://www.jxxdxy.edu.cn",
    logo: "",
    militaryTraining: "10月初，约10-14天",
    dormitory: "昌东校区，4-6人间，有空调、独卫",
    cafeteria: "有2个食堂",
    campusArea: "约1000亩",
    majors: "建筑工程技术、电子商务、电子信息、材料工程",
    tuition: "5000-6000元/年",
    transportation: "地铁1号线艾溪湖东站附近",
    genderRatio: "男:女 ≈ 3:2",
    clubs: "50+社团",
    description: "双高计划建设院校，综合实力省内高职前列"
  },
  {
    id: 48,
    name: "江西交通职业技术学院",
    level: "公办高职 / 双高计划",
    city: "南昌",
    website: "https://www.jxjtxy.edu.cn",
    logo: "",
    militaryTraining: "10月初，约10-14天",
    dormitory: "经开区校区，4-6人间，有空调",
    cafeteria: "有2个食堂",
    campusArea: "约800亩",
    majors: "道路桥梁工程、汽车检测与维修、城市轨道交通、物流管理",
    tuition: "5000-6000元/年",
    transportation: "地铁1号线可达",
    genderRatio: "男:女 ≈ 5:1",
    clubs: "40+社团",
    description: "双高计划建设院校，交通运输类专业省内最强"
  },
  {
    id: 49,
    name: "江西外语外贸职业学院",
    level: "公办高职 / 国家骨干",
    city: "南昌",
    website: "https://www.jxcfs.edu.cn",
    logo: "",
    militaryTraining: "10月初，约10天",
    dormitory: "瑶湖校区，4人间为主，有空调、独卫",
    cafeteria: "有2个食堂",
    campusArea: "约600亩",
    majors: "商务英语、国际经济与贸易、电子商务、翻译",
    tuition: "5000-6000元/年",
    transportation: "地铁1号线瑶湖西站附近",
    genderRatio: "男:女 ≈ 1:3",
    clubs: "40+社团，外语角活动丰富",
    description: "国家骨干高职院校，外语外贸特色鲜明，就业率高"
  },
  {
    id: 50,
    name: "江西环境工程职业学院",
    level: "公办高职 / 双高计划",
    city: "赣州",
    website: "https://www.jxhjxy.edu.cn",
    logo: "",
    militaryTraining: "10月中旬，约10-14天",
    dormitory: "蓉江新区校区，4-6人间，有空调",
    cafeteria: "有食堂",
    campusArea: "约1000亩",
    majors: "环境工程技术、园林技术、家具设计、林业技术",
    tuition: "5000元/年",
    transportation: "赣州站公交可达",
    genderRatio: "男:女 ≈ 2:1",
    clubs: "30+社团",
    description: "双高计划建设单位，林业与环境保护类专业省内唯一"
  },
  {
    id: 51,
    name: "江西应用技术职业学院",
    level: "公办高职 / 双高计划",
    city: "赣州",
    website: "https://www.jxyyxy.edu.cn",
    logo: "",
    militaryTraining: "10月中旬，约10-14天",
    dormitory: "蓉江校区，4-6人间，有空调",
    cafeteria: "有食堂",
    campusArea: "约800亩",
    majors: "国土资源管理、测绘地理信息、工业机器人、汽车检测",
    tuition: "5000-6000元/年",
    transportation: "赣州站公交可达",
    genderRatio: "男:女 ≈ 3:1",
    clubs: "30+社团",
    description: "双高计划建设院校，国土资源与测绘类专业有优势"
  },
  {
    id: 52,
    name: "江西旅游商贸职业学院",
    level: "公办高职",
    city: "南昌",
    website: "https://www.jxlsxy.edu.cn",
    logo: "",
    militaryTraining: "10月初，约10天",
    dormitory: "昌北校区，4-6人间，有空调",
    cafeteria: "有2个食堂",
    campusArea: "约1000亩",
    majors: "旅游管理、酒店管理、烹饪工艺、电子商务",
    tuition: "5000元/年",
    transportation: "地铁可达",
    genderRatio: "男:女 ≈ 1:2",
    clubs: "40+社团",
    description: "旅游商贸类专业齐全，与省内旅游企业合作紧密"
  },
  {
    id: 53,
    name: "江西电力职业技术学院",
    level: "公办高职",
    city: "南昌",
    website: "https://www.jxdlzy.edu.cn",
    logo: "",
    militaryTraining: "10月初，约10-14天",
    dormitory: "经开区校区，4-6人间，有空调",
    cafeteria: "有食堂",
    campusArea: "约500亩",
    majors: "电力系统自动化、发电厂及电力系统、新能源装备技术",
    tuition: "5000元/年",
    transportation: "地铁可达",
    genderRatio: "男:女 ≈ 5:1",
    clubs: "30+社团",
    description: "国家电网公司系统内院校，电力系统就业率高"
  },
  {
    id: 54,
    name: "江西机电职业技术学院",
    level: "公办高职",
    city: "南昌",
    website: "https://www.jxjdxy.edu.cn",
    logo: "",
    militaryTraining: "10月初，约10-14天",
    dormitory: "经开区校区，4-6人间，有空调",
    cafeteria: "有食堂",
    campusArea: "约500亩",
    majors: "机电一体化、数控技术、工业机器人、新能源汽车",
    tuition: "5000-6000元/年",
    transportation: "地铁可达",
    genderRatio: "男:女 ≈ 6:1",
    clubs: "30+社团",
    description: "机电制造类专业优势突出，实训设备省内领先"
  },
  {
    id: 55,
    name: "江西工业贸易职业技术学院",
    level: "公办高职",
    city: "南昌",
    website: "https://www.jxgmxy.edu.cn",
    logo: "",
    militaryTraining: "10月初，约10-14天",
    dormitory: "湾里校区，4-6人间，有空调",
    cafeteria: "有食堂，另有美食街",
    campusArea: "约600亩",
    majors: "食品营养与检测、粮食工程、电子商务、市场营销",
    tuition: "5000元/年",
    transportation: "公交可达",
    genderRatio: "男:女 ≈ 1:1",
    clubs: "30+社团",
    description: "粮食和食品类专业省内独有，与粮油企业合作紧密"
  },
  {
    id: 56,
    name: "江西建设职业技术学院",
    level: "公办高职",
    city: "南昌",
    website: "https://www.jxjsxy.edu.cn",
    logo: "",
    militaryTraining: "10月初，约10-14天",
    dormitory: "昌北校区，4-6人间，有空调",
    cafeteria: "有食堂",
    campusArea: "约500亩",
    majors: "建筑工程技术、工程造价、建筑设计、市政工程",
    tuition: "5000-6000元/年",
    transportation: "地铁可达",
    genderRatio: "男:女 ≈ 4:1",
    clubs: "30+社团",
    description: "建筑类专业齐全，与省建工集团等企业深度合作"
  },
  {
    id: 57,
    name: "江西卫生职业学院",
    level: "公办高职",
    city: "南昌",
    website: "https://www.jxwzy.edu.cn",
    logo: "",
    militaryTraining: "10月初，约10天",
    dormitory: "湾里校区，4-6人间，有空调",
    cafeteria: "有食堂",
    campusArea: "约500亩",
    majors: "护理、助产、药学、医学检验技术",
    tuition: "5000元/年",
    transportation: "公交可达",
    genderRatio: "男:女 ≈ 1:4",
    clubs: "30+社团，医疗卫生志愿服务突出",
    description: "省内主要的医护人才培养基地，附属医院实习资源丰富"
  },
  {
    id: 58,
    name: "江西工业工程职业技术学院",
    level: "公办高职",
    city: "萍乡",
    website: "https://www.jxgcxy.edu.cn",
    logo: "",
    militaryTraining: "10月中旬，约10-14天",
    dormitory: "安源校区，4-6人间，有空调",
    cafeteria: "有食堂",
    campusArea: "约500亩",
    majors: "煤矿安全技术、机电一体化、建筑工程技术",
    tuition: "5000元/年",
    transportation: "萍乡站公交可达",
    genderRatio: "男:女 ≈ 4:1",
    clubs: "20+社团",
    description: "工科类高职院校，矿业安全和机电类专业有行业背景"
  },
  {
    id: 59,
    name: "宜春职业技术学院",
    level: "公办高职",
    city: "宜春",
    website: "https://www.ycvc.edu.cn",
    logo: "",
    militaryTraining: "10月中旬，约10-14天",
    dormitory: "袁州校区，4-6人间，有空调",
    cafeteria: "有食堂",
    campusArea: "约500亩",
    majors: "护理、学前教育、电子商务、机电一体化",
    tuition: "5000元/年",
    transportation: "宜春站公交可达",
    genderRatio: "男:女 ≈ 1:3",
    clubs: "30+社团",
    description: "赣西地区综合性高职院校，医护和学前教育为特色"
  },
  {
    id: 60,
    name: "吉安职业技术学院",
    level: "公办高职",
    city: "吉安",
    website: "https://www.japt.edu.cn",
    logo: "",
    militaryTraining: "10月中旬，约10-14天",
    dormitory: "吉州校区，4-6人间，有空调",
    cafeteria: "有食堂",
    campusArea: "约500亩",
    majors: "电子信息、机械制造、旅游管理、学前教育",
    tuition: "5000元/年",
    transportation: "吉安站/吉安西站公交可达",
    genderRatio: "男:女 ≈ 3:2",
    clubs: "30+社团",
    description: "吉安市属高职院校，对接本地电子信息产业"
  }
];

// 导出数据（兼容不同引用方式）
if (typeof module !== 'undefined' && module.exports) {
  module.exports = universities;
}
